import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#131313",
        "inverse-primary": "#ad3300",
        "on-secondary-fixed-variant": "#004f4f",
        "on-tertiary": "#3b2f00",
        "tertiary-fixed": "#ffe179",
        "secondary-container": "#007f7f",
        "surface-container-high": "#2a2a2a",
        "primary-fixed": "#ffdbd0",
        "on-tertiary-container": "#4d3e00",
        "secondary": "#76d6d5",
        "surface-variant": "#353534",
        "surface-dim": "#131313",
        "on-secondary-fixed": "#002020",
        "error": "#ffb4ab",
        "on-secondary-container": "#ddfffe",
        "on-background": "#e5e2e1",
        "error-container": "#93000a",
        "surface-bright": "#393939",
        "primary": "#ffb59e",
        "outline": "#ac897e",
        "tertiary-fixed-dim": "#e6c443",
        "on-tertiary-fixed": "#231b00",
        "secondary-fixed-dim": "#76d6d5",
        "surface-container-highest": "#353534",
        "on-error": "#690005",
        "on-surface": "#e5e2e1",
        "on-primary-container": "#521300",
        "surface-tint": "#ffb59e",
        "on-primary": "#5e1700",
        "inverse-surface": "#e5e2e1",
        "on-surface-variant": "#e6beb2",
        "on-primary-fixed-variant": "#842500",
        "primary-fixed-dim": "#ffb59e",
        "outline-variant": "#5c4037",
        "primary-container": "#ff5717",
        "surface-container-low": "#1c1b1b",
        "on-tertiary-fixed-variant": "#554500",
        "background": "#131313",
        "surface-container": "#201f1f",
        "tertiary-container": "#c9a828",
        "tertiary": "#e6c443",
        "surface-container-lowest": "#0e0e0e",
        "inverse-on-surface": "#313030",
        "on-secondary": "#003737",
        "secondary-fixed": "#93f2f2",
        "on-primary-fixed": "#3a0b00",
        "on-error-container": "#ffdad6"
      },
      fontFamily: {
        headline: ["var(--font-inter)"],
        body: ["var(--font-newsreader)"],
        label: ["var(--font-inter)"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      animation: {
        'spin-slow': 'spin 3s linear infinite',
      }
    },
  },
  plugins: [],
};
export default config;
